version: 1.0.{build}

branches:
  only:
    - master

skip_branch_with_pr: true

image: Visual Studio 2017

matrix:
  fast_finish: true

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

platform: Any CPU

configuration: Release

before_build:
  - nuget restore

build:
  parallel: true
  project: Mixin.sln
  publish_nuget: true
  publish_nuget_symbols: true

  verbosity: normal

test:
  assemblies:
    - Mixin.Tests.dll

artifacts:
  - path: 'bin\$(configuration)\*.nupkg'

deploy:
  - provider: NuGet
    artifact: /.*\.nupkg/
    api_key: $(NUGET_PRIVATE_KEY)